# Generated by Django 4.0 on 2022-04-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('authentication', '0002_alter_employer_nature of business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.basemodel')),
                ('title', models.CharField(max_length=225)),
                ('content', models.CharField(max_length=225)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'verbose_name': 'Announcement',
            },
            bases=('config.basemodel',),
        ),
    ]
