# Generated by Django 4.0.4 on 2022-05-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.basemodel')),
                ('title', models.CharField(max_length=225)),
                ('content', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Announcement',
            },
            bases=('config.basemodel',),
        ),
    ]
