# Generated by Django 4.0.4 on 2022-05-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
