# Generated by Django 4.0.4 on 2022-04-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_alter_jobpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
