# Generated by Django 4.0.4 on 2022-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='Status',
            new_name='status',
        ),
    ]
