# Generated by Django 4.0.4 on 2022-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_employer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='contact',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
