# Generated by Django 4.0.4 on 2022-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_employer_nature of business'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile_picture/'),
            preserve_default=False,
        ),
    ]
