# Generated by Django 4.0.4 on 2022-04-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_employer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='Nature of Business',
            new_name='business_nature',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='Company Address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='Company Name',
            new_name='company_name',
        ),
    ]
