# Generated by Django 4.0.4 on 2022-04-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_nature of business_employer_business_nature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Previous employer/s (*if you have working experience)',
            new_name='prev_employer',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Have working experience?',
            new_name='working_exp',
        ),
    ]
