# Generated by Django 4.0.4 on 2022-04-27 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_address_applicant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_applicant', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
