# Generated by Django 4.0 on 2022-04-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_employer_nature of business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='birthdate',
            new_name='dd/mm/yy',
        ),
    ]
