# Generated by Django 4.0.4 on 2022-04-27 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobpost', '0003_alter_jobpost_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0002_rename_status_basemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.basemodel')),
                ('resumes', models.FileField(upload_to='resumes/')),
                ('additional_info', models.TextField(max_length=500)),
                ('already_applied', models.BooleanField(default=True)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('config.basemodel',),
        ),
        migrations.CreateModel(
            name='ApplicantRequirement',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.basemodel')),
                ('requirements_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='requirements/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('config.basemodel',),
        ),
    ]
