# Generated by Django 4.0.4 on 2022-05-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantRequirement',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.basemodel')),
                ('requirements_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='requirements/')),
            ],
            bases=('config.basemodel',),
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.basemodel')),
                ('resumes', models.FileField(upload_to='resumes/')),
                ('additional_info', models.TextField(max_length=500)),
                ('already_applied', models.BooleanField(default=True)),
                ('approved', models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=255)),
            ],
            bases=('config.basemodel',),
        ),
    ]
