# Generated by Django 4.0.4 on 2022-04-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
