# Generated by Django 4.0.4 on 2022-05-03 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0001_initial'),
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantrequirement',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost'),
        ),
        migrations.AddField(
            model_name='applicantrequirement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
